// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:2f691593-1083-4252-b032-ea213ca733cd",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_TOEApzVWe",
    "aws_user_pools_web_client_id": "56h7u3aem1qh2fj7h047a05ld8"
};


export default awsmobile;
